Organizar los scripts de /usr/local/bin, usar el salvapantallas por defecto. Y otras pequeñas actualizaciones.

diff --git a/modules/audio-setup b/modules/audio-setup
--- a/modules/audio-setup
+++ b/modules/audio-setup
@@ -6,25 +6,17 @@
 
 # Configurar el audio de baja latencia
 
-# Verificar si el script se ejecuta como root
-if [ "$(id -u)" -ne 0 ]; then
-	echo "Error: Este script debe ejecutarse como root." >&2
-	exit 1
-fi
-
-# Obtener el nombre de usuario con UID 1000 (generalmente el primer usuario no root)
-RUSER="$(getent passwd 1000 | cut -d: -f1)"
-if [ -z "$RUSER" ]; then
-	echo "Error: No se pudo encontrar un usuario con UID 1000." >&2
+if [ "$(id -u)" -eq 0 ]; then
+	echo "Error: Este script no debe ejecutarse como root." >&2
 	exit 1
 fi
 
 # Añadimos el usuario a los grupos desados
-usermod -aG realtime,audio,video,optical,uucp "$RUSER"
+sudo usermod -aG realtime,audio,video,optical,uucp "$USER"
 
 # Permite al usuario (en el grupo "audio") utilizar dispositivos de audio con
 # prioridad elevada y acceso a recursos extendidos.
-cat <<-EOF | tee -a /etc/security/limits.conf
+cat <<-EOF | sudo tee -a /etc/security/limits.conf
 	    @audio - rtprio 95
 	    @audio - memlock unlimited
 	    $RUSER hard nofile 524288
diff --git a/modules/root/set-clock b/modules/root/set-clock
--- a/modules/root/set-clock
+++ b/modules/root/set-clock
@@ -15,14 +15,10 @@ fi
 
 # Obtener la zona horaria actual
 TIMEZONE="$(readlink -f /etc/localtime | sed 's|.*/zoneinfo/||')"
-if [ -z "$TIMEZONE" ]; then
-	echo "Error: No se pudo determinar la zona horaria del sistema." >&2
-	exit 1
-fi
 
 # Verificar dependencias
 if ! command -v jq &>/dev/null; then
-	echo "Error: El comando 'jq' no está instalado. Por favor, instálelo antes de ejecutar este script." >&2
+	echo "Error: jq no está instalado." >&2
 	exit 1
 fi
 
@@ -32,21 +28,9 @@ CURRENT_TIME=""
 
 # Función para obtener la hora desde una API
 get_current_time() {
-	local api="$1"
-	case "$api" in
-	worldtimeapi)
-		curl "http://worldtimeapi.org/api/timezone/$TIMEZONE" |
-			jq -r '.datetime' | cut -d. -f1 | sed 's/T/ /'
-		;;
-	timeapi)
-		curl -s \
-			"https://timeapi.io/api/Time/current/zone?timeZone=$TIMEZONE" |
-			grep -oP '"dateTime":"\K[^"]+' | cut -d. -f1 | sed 's/T/ /'
-		;;
-	*)
-		return 1
-		;;
-	esac
+	curl -s \
+		"https://timeapi.io/api/Time/current/zone?timeZone=$TIMEZONE" |
+		grep -oP '"dateTime":"\K[^"]+' | cut -d. -f1 | sed 's/T/ /'
 }
 
 # Intentar obtener la hora hasta que se defina o se alcance el límite de intentos
@@ -54,11 +38,7 @@ while [ -z "$CURRENT_TIME" ] && [ "$COUNTER" -le 5 ]; do
 	echo "Intento $COUNTER: Obteniendo la hora..."
 
 	# Primero intentar con worldtimeapi
-	CURRENT_TIME=$(get_current_time "worldtimeapi")
-	if [ -z "$CURRENT_TIME" ]; then
-		# Si falla, intentar con timeapi
-		CURRENT_TIME=$(get_current_time "timeapi")
-	fi
+	CURRENT_TIME=$(get_current_time)
 
 	# Incrementar el contador y esperar antes del siguiente intento
 	if [ -z "$CURRENT_TIME" ]; then
diff --git a/modules/root/sudo2doas b/modules/root/sudo2doas
--- a/modules/root/sudo2doas
+++ b/modules/root/sudo2doas
@@ -42,6 +42,9 @@ fi
 echo "Instalando doas-sudo-shim..."
 if command -v yay &>/dev/null; then
 	su "$RUSER" -c "yay -Sy --noconfirm --disable-download-timeout --needed doas-sudo-shim"
+else
+	echo "Error: yay no está instalado." >&2
+	exit 1
 fi
 
 # Mensaje final
